### ISSUE TITLE
Full database

### ISSUE THREAD

**Issue by athammad** [yhyhpan/COVID19_LOCKDOWN#2]
Hi,

first of all, you are analysis is very interesting and well done.

Could you please tell me when the full database will be available? 

Many thanks

**Comment by yhyhpan** [comment]
Hi Ahmed,

Thanks for your interests on the project. The database on lockdown and air
pollutants is available already in that folder. Should you have further
questions, pls feel free to contact me.

Best,
Yuhang

**Comment by athammad** [comment]
Hi,
I can run your code only partially. For example I cannot run the the heterogeneity effects analysis and the analysis on the spillover effects like in  the _Supplementary Table 8. Robustness Check Using Different Subsamples_. The latter would be very interesting for me.

Any advice on this?

**Comment by athammad** [comment]
Or could you provide information to link the city code to the actual city name?

Best wishes

**Comment by yhyhpan** [comment]
Hi Ahmed,

Yes, for the subsample one, we (1) just drop the hubei province sample (indicated by hubei variable), and (2) drop the neighbour cities of lockdown cities. I updated the codes for these.

Best,
Yuhang

**Comment by athammad** [comment]
Hi Yuhang,

thank you for the update. Is there anyway to match the code of a city with its name? 
For example code 87544  to city ABCD, code 100304 to city EFGH?
Btw, I think the issue #3 is asking exactly the same thing like my last question.

If you could help in this that would be much appreciated.

Best wishes,
Ahmed

**Comment by yhyhpan** [comment]
> Hi Yuhang,
> 
> thank you for the update. Is there anyway to match the code of a city with its name?
> For example code 87544 to city ABCD, code 100304 to city EFGH?
> Btw, I think the issue #3 is asking exactly the same thing like my last question.
> 
> If you could help in this that would be much appreciated.
> 
> Best wishes,
> Ahmed

Hi Ahmed,

We already put the lockdown status in the appendix (as city's Chinese pinyin name and the timing of lockdown). Will it be okay for your needs?

**Comment by athammad** [comment]
Hi Yuhang,

I have seen the appendix but I need to link the city name with the city code to use them in the analysis. 
Could you please provide this information?
I am sending you an email following your answer to issue #3 

Best wishes,
Ahmed
