### ISSUE TITLE
how can I match the real_city_name  using city_code in wf.dta ???

### ISSUE THREAD

**Issue by J08056** [yhyhpan/COVID19_LOCKDOWN#3]
Dear yhyhpan,
I'm very interested in your paper! For  my further research, I'd like to adopt your criteria for city-lockdown. can you show me how I can match the real_city_name  using city_code in wf.dta.

**Comment by yhyhpan** [comment]
Hi, we have already attached the real_city_name (in Chinese pinyin name) with lockdown status in the paper appendix. Or you can send your request to me (yhyhpan@gmail.com) to see whether you have further needs?
